# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Manuscript catalogs
tagline:          'Text contents of digital manuscripts'
description:      'Cataloging the text contents of manuscripts illustrated by openly licensed digital images'

baseurl: '/msscatalog'


author:
  name:           'Neel Smith'
 

paginate:         5


version:          0.12.0


links:
  - title: Open Manuscripts initiative
    url: http://openmss.github.io/
    external: true
  - title: Github repository for this project
    url: https://github.com/openmss/msscatalog
    external: true
